# Generated by Django 4.0.4 on 2022-04-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telef',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
