# Generated by Django 4.0.4 on 2022-04-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_cliente_dni_alter_cliente_telef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, default='--------', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telef',
            field=models.CharField(blank=True, default='-----------', max_length=13, null=True),
        ),
    ]
